### ISSUE TITLE
Connection Timeout Glitch/Abuse

### ISSUE THREAD

**Issue by dachangjames** [ccu-dorm-for-grads/ccu-dorm-for-grads#66]
When opening /index.php, there will be **a slight chance** that the database cannot be connected in time, thus making the PHP page unable to load the dormitory system but showing the error message instead, which should not be displayed to normal users.
![ConnectionTimeout](https://github.com/ccu-dorm-for-grads/ccu-dorm-for-grads/assets/91360472/b55d104a-a9d4-4856-9024-6ff3cf54e11b)

**Comment by WaltsonZh** [comment]
??????????
