### ISSUE TITLE
Weird operation with adm and dep privileges

### ISSUE THREAD

**Issue by dachangjames** [ccu-dorm-for-grads/ccu-dorm-for-grads#71]
Users with adm and dep privileges can add new students to sl8gdm_dep_stuapply, even if the students' respective student id (sid) is not on the list of sl8gdm_permit_rec. That is, users with adm and dep privileges can inherently add whatever shit they want into the sl8gdm_dep_stuapply table.

Note: This is just a suggestion about patching a loophole I discovered during the development of admapply.php and admapply_unit.php. You can close this issue whenever you want.
![bandicam 2023-12-19 03-08-26-716](https://github.com/ccu-dorm-for-grads/ccu-dorm-for-grads/assets/91360472/acb56c1b-15a5-4162-afcf-7ad7b292c551)

**Comment by WaltsonZh** [comment]
@jasonbombbro 是你嗎

**Comment by WaltsonZh** [comment]
This is not a loophole but a black hole in the project.
We've discussed this hazard in previous meetings, and we really can't do much about it.
We don't have time to refactor and adjust previous code base that are having potential conflicts with the new database. 🫠🫠🫠

**Comment by jasonbombbro** [comment]
> @jasonbombbro 是你嗎

這次不是我，我發誓
