### ISSUE TITLE
到底誰是蜂窩性祖師爺 😡😡😡

### ISSUE THREAD

**Issue by WaltsonZh** [ccu-dorm-for-grads/ccu-dorm-for-grads#73]
![img](https://private-user-images.githubusercontent.com/91360472/291384304-acb56c1b-15a5-4162-afcf-7ad7b292c551.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjUyMTEsIm5iZiI6MTcwMjk2NDkxMSwicGF0aCI6Ii85MTM2MDQ3Mi8yOTEzODQzMDQtYWNiNTZjMWItMTVhNS00MTYyLWFmY2YtN2FkN2IyOTJjNTUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA1NDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNDJjZTNjZTIzMmExMTRhODBiYWRiMzRmNmIwMjk3ZmEzMWRkNzg5NTg3Yzg0MGMxODEyNTRjYzU0YzcwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ym8lO0T5adzLSKSGGXoEIRU8J76bTBg_65TLv88cyA)

**Comment by jasonbombbro** [comment]
沒有圖片

**Comment by wh00am1** [comment]
6

**Comment by Tail001** [comment]
是誰很明顯了吧
